#! /bin/sh

#Reference: Mastering-embedded-linux-programming Chapter 10

case "$1" in
  start)
    echo "Starting module load"
    start-stop-daemon -S -n scull -a /usr/bin/scull_load
    start-stop-daemon -S -n faulty -a /usr/bin/module_load -- faulty
    modprobe hello
    ;;
  stop)
    echo "Stopping module load"
    start-stop-daemon -K -n scull
    start-stop-daemon -K -n scull
    rmmod hello
    ;;
  *)
  echo "Usage: $0 {start|stop}"
  exit 1
esac
exit 0
